

###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "firstName" :"Brian",
    "lastName" :"Gakenye",
    "email":"codewithgakenye@gmail.com",
    "password":"12345678",
    "contactPhone": "0112310754",
    "address": "50 Nyeri",
    "role":"admin"    
}

###
GET http://localhost:5000/api/AllUsers


###
GET  http://localhost:5000/api/User/4


###
GET http://localhost:5000/api/search-user?lastName=gake

###
###
PUT  http://localhost:5000/api/update-User/1
Content-Type: application/json

{
    "firstName" :"BRIAN"    
}


###
DELETE http://localhost:5000/api/delete-User/1

###
GET http://localhost:5000/api/get-All-User-Details/4

# products Routes
###
GET http://localhost:5000/api/All-Products

###
POST http://localhost:5000/api/create-Product
Content-Type: application/json

{
    "title":"Air Jordan 4",
    "description":"Colorway: White/Fire Red/Black/Tech GreyThe Air Jordan 4 Retro returns with a clean blend of classic design and modern comfort. Featuring a premium leather upper in a crisp white base, bold Fire Red accents, and black and grey detailing, this iconic silhouette stands out on and off the court.",
    "price":"4000",
    "stock": "100"
}


###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email":"brayogakenye04@gmail.com",
    "password":"Gakenye123#"
}

#categries
###
POST http://localhost:5000/api/add-category 
Content-Type: application/json

{
    "name":"Clothes"
}

###
GET http://localhost:5000/api/all-categories

# subcategories
###
GET http://localhost:5000/api/all-subcategories

###
POST http://localhost:5000/api/add-subcategory
Content-Type: application/json

{
    "name":"Airforce",
     "categoryId": 2
}

###
GET http://localhost:5000/api/subcategory-content/6

###
GET http://localhost:5000/api/All-Products


###
DELETE http://localhost:5000/api/delete-Product/8

###
PUT http://localhost:5000/api/update-Product/10
Content-Type: application/json

{
  "title": "Updated Product Title",
  "description": "Updated description here.",
  "price": 49.99,
  "stock": 120,
  "subcategoryId": 3
}

#IMAGES
### Upload a new image (POST)
POST http://localhost:5000/api/create-Image
Content-Type: application/json

{
  "productId": "11",
  "imageUrl": "https://res.cloudinary.com/dwibg4vvf/image/upload/v1691496472/sample.jpg",
  "alt": "Sample Product Image"
}


### Get all images
GET http://localhost:5000/api/AllImages

### Get image by ID
GET http://localhost:5000/api/Image/1

### Get images by productId
GET http://localhost:5000/api/ProductImages/11

### Create a new image
POST http://localhost:5000/api/create-Image
Content-Type: application/json

{
  "productId": 11,
  "url": "https://example1.com/image.jpg",
  "alt": "Example image"
}

### Update image
PUT http://localhost:5000/api/update-Image/1
Content-Type: application/json

{
  "url": "https://example.com/updated.jpg",
  "alt": "Updated alt text"
}

### Delete image
DELETE http://localhost:5000/api/delete-Image/1

###
POST http://localhost:5000/api/create-OrderItem
Content-Type: application/json

{
  "orderId": 19,
  "productId": 20,
  "quantity": 2,
  "price": 3500.00
}


###
GET http://localhost:5000/api/AllOrders

###
POST http://localhost:5000/api/create-Order
Content-Type: application/json

{
   "userId": 480223717,
   "totalAmount": 5000
}
